### ISSUE TITLE
SSL error on CDN

### ISSUE THREAD

**Issue by nabilragab** [wp-statistics/GeoLite2-City#3]
Resolving cdn.jsdelivr.net (cdn.jsdelivr.net)... 104.16.85.20, 104.16.87.20, 104.16.88.20, ...
Connecting to cdn.jsdelivr.net (cdn.jsdelivr.net)|104.16.85.20|:443... connected.
OpenSSL: error:0A000126:SSL routines::unexpected eof while reading
Unable to establish SSL connection.

**Comment by mostafasoufi** [comment]
Hey,

Are you connected from China? related issue https://github.com/jsdelivr/jsdelivr/issues/18348

**Comment by jimaek** [comment]
If you're from Egypt please note that some Egyptian ISPs are blocking cdn.jsdelivr.net on their side, its not a jsDelivr issue.
Consider contacting your ISP directly to get this issue fixed, try using a VPN or change the hostname to fastly.jsdelivr.net.
Feel free to give your ISP my email dak@prospectone.io in case they have questions

**Comment by mostafasoufi** [comment]
Thank you for providing the information @jimaek
